version: '3'
services:
  db:
    image: mysql:latest
    volumes:
      - ./data:/var/lib/mysql
    container_name: db-service
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: therootpassword
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}