version: '3'
services:
  poc-service:
    depends_on:
      - db
    image: openjdk:8-jre
    volumes:
      - ./build/libs:/app
    container_name: poc-service
    command: java -Xmx2g -jar /app/starter-spring-jpa-mysql-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080
  db:
    image: mysql:latest
    volumes:
      - ./data:/var/lib/mysql
    container_name: db-service
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: therootpassword
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}